
version: '3.4'

services:
  wallet-watcher:
    image: wallet-watcher:${TAG:-latest}
    environment:
      - APP_ENVIRONMENT=Production
    build:
      context: .
      dockerfile: src/Pathin.WalletWatcher/Dockerfile
