FROM mcr.microsoft.com/dotnet/runtime:7.0 AS base
WORKDIR /app

COPY "../../appsettings.json" "../../appsettings.json"
COPY "../../appsettings.Development.json" "../../appsettings.Development.json"

# VSDBG
RUN apt-get update && apt-get install -y \
    curl
RUN curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -v latest -l /vsdbg

ENTRYPOINT ["tail", "-f", "/dev/null"]